assistant_task:
  description: >
    Read the content of the dictionary with the conversations from the past 24 hours and create a 
    one-paragraph summary pointing out the most important messages.
    The content of the messages is in a dictionary called messages.
    These are the messages: {messages}
  expected_output: >
    A one-paragraph in Portuguese with a summary of the most important conversations from the past 24 hours
  agent: assistant